- python_libs/pebble-loghash/pebble/loghashing/newlogging.py
- tools/gdb_driver.py
- tools/gdb_scripts/gdb_heap.py
- tools/gdb_scripts/gdb_parser.py
- tools/gdb_scripts/gdb_python_path_fix.py
- tools/gdb_scripts/gdb_tintin.py
- tools/gdb_scripts/gdb_utils.py
- tools/log_hashing/check_elf_log_strings.py
- tools/log_hashing/logdehash.py
- tools/log_hashing/newlogging.py
- tools/pebble_tty.py
- tools/pebble_tty_pyftdi.py
- waftools/openocd.py
These changes (mostly) make waf console work with loghashing, with the exception that for some boards it expects to use a private fork of pyftdi. The changes were mostly just to add custom VID/PIDs for bigboards - I'll make some changes separately to make this work with a public version of that package.
Tested with snowy_bb2/silk_bb2 (separate changes to come to fix those board builds).
> Updates for Python 3 compatibility

- tools/bitmapgen.py
- tools/generate_pdcs/pebble_commands.py
- waftools/binary_header.py
- waftools/sparse_length_encoding.py
These changes are required to build snowy/spalding/silk.
> tools: fix resource generation tools for Python 3

- waftools/clang_compilation_database.py
Fix `waf` generation of `compile_commands.json` when the `--compile_commands` config option is specified.
I've adapted the workaround already used in `sdk/waf/waflib/extras/clang_compilation_database.py` (the `write_compilation_database` method of the `ClangDbContext` class), which runs each `task` with a temporarily disabled `exec_command` in order to obtain the task's `last_cmd`.
When generating the `compile_commands.json` the `commands` field has been replaced with `arguments`, since the [database documentation](https://clang.llvm.org/docs/JSONCompilationDatabase.html) mentions that it is preferred. 
> Either arguments or command is required. arguments is preferred, as shell (un)escaping is a possible source of errors.
Tested on Fedora 41, in VSCode, using the following …
> build: fix waf generation of compile_commands.json

- .github/workflows/build.yml
- README.md
- src/fw/applib/rockyjs/api/rocky_api_graphics_color.c
- src/fw/vendor/jerryscript/js_tooling/_js_tooling.js
- src/fw/vendor/jerryscript/js_tooling/js_tooling_port.c
- src/fw/vendor/jerryscript/js_tooling/transform_js.py
- src/fw/vendor/jerryscript/wscript
- tools/resources/resource_map/resource_generator_js.py
- waftools/c_inject_include_files.py
> fw: fix building with JS support

- tools/font/dump_font.py
- tools/font/fontgen.py
Fixes https://github.com/pebble-dev/pebble-firmware/issues/44
> Fix broken fonts where regex filter is used

- src/fw/apps/system_apps/settings/settings_system.c
- tools/font/fontgen.py
- waftools/gitinfo.py
If you'd prefer I split these into two separate PRs, I can absolutely do so.
> Python compatibility fix, and System > Information > Firmware improvement

- waftools/openocd.py
- waftools/openocd_swd_cmsisdap.cfg
- waftools/openocd_swd_jlink.cfg
- wscript
Introduce some OpenOCD fixes/updates, tested with https://github.com/pebble-dev/openocd.
> Some OpenOCD fixes/updates

- README.md
- docs/porting-bluetooth.md
Leftover doc changes from #47.
> doc: bluetooth port guide

- wscript
Small change in the wscript that fixes the ./waf bundle command
> waf: fix waf bundle

- src/fw/FreeRTOSConfig.h
- src/fw/vendor/FreeRTOS/Source/light_mutex.c
- src/fw/vendor/FreeRTOS/Source/queue.c
- third_party/nimble/port/src/npl_os_pebble.c
Some FreeRTOS tweaks and porting layer fixes, see commit messages for more details.
> Some updates related to NimBLE

- src/bluetooth-fw/nimble/gatt_client_discovery.c
I'm actually not thrilled with the way I ended up implementing this and will rejig it later to use less heap.
> bluetooth: implement gatt client discovery

- third_party/nimble/transport/chipset/cc2564.c
- third_party/nimble/transport/hci_uart_transport.c
Fixes #104
I'm a little wary of doing this while we're still hitting the HCI crash, but figure I'd leave it here ready since I expect it'll speed up things like app install/FWUP quite a bit.
> bluetooth: implement baud rate switch for cc2564x

- .github/workflows/build.yml
- .github/workflows/test.yml
- .readthedocs.yaml
e.g. skip building/testing if only touching docs.
> ci: only build/test if modifying relevant paths

- docs/getting_started.md
Add some improvements now that I had a chance to test it on a macOS machine that had no development crap installed.
> docs: update getting started guide

- resources/normal/base/lang/wscript
- tools/generate_codepoint_requirements.py
fix `./waf` commands `pack_lang` and `pack_all_langs`
fixes #187
> i18n: fix languages packing

- src/fw/comm/ble/gap_le_advert.c
We should not try to advertise while connected. Even though NimBLE layer will just handle this, let's avoid executing unnecessary code that we know it is gonna fail.
Note that after a successful connection, kernel_le_client.c will unschedule jobs accordingly, but until this happens, the cycle timer can still trigger.
> fw/comm/ble/advert: handle connected state

- src/fw/board/board_nrf5.h
- src/fw/board/boards/board_asterix.c
- src/fw/board/boards/board_asterix.h
- src/fw/drivers/display/sharp_ls013b7dh01/sharp_ls013b7dh01_nrf5.c
- third_party/hal_nordic/wscript
- Generate EXTCOMIN pulses
- Reduce SPI frequency to maximum allowed by the display
EXTCOMIN verified on board:
> Adjust some Asterix display stuff

- src/fw/console/dbgserial.c
- src/fw/drivers/i2c.c
- src/fw/drivers/i2c_definitions.h
As soon as one starts cleaning up board headers this happens.
> fw: add some missing includes

- .github/workflows/build-translation-source.yml
- .github/workflows/crowdin-pull.yml
- crowdin.yml
- resources/normal/base/lang/tintin.pot
Requires CROWDIN_PROJECT_ID and CROWDIN_PERSONAL_TOKEN to be set in secrets
> ci: add Crowdin integration for translation support

- .github/workflows/build-translation-source.yml
Missed a small thing while doing some last minute changes in #185 . 
Will close #232 
Thanks @gmarull for notifying me!
> ci: do not build translation on pr

- .gitignore
- src/bluetooth-fw/nimble/advert.c
- src/bluetooth-fw/nimble/gap_le_connect.c
- src/bluetooth-fw/nimble/gap_le_device_name.c
- src/bluetooth-fw/nimble/gatt_client_discovery.c
- src/bluetooth-fw/nimble/gatt_client_operations.c
- src/bluetooth-fw/nimble/init.c
- src/bluetooth-fw/nimble/nimble_type_conversions.c
- src/bluetooth-fw/nimble/pairing_confirm.c
- src/bluetooth-fw/nimble/pebble_pairing_service.c
- src/bluetooth-fw/nimble/responsiveness.c
- src/fw/comm/ble/gatt.c
- src/fw/comm/ble/gatt_client_discovery.c
- src/fw/comm/ble/gatt_client_subscriptions.c
- third_party/nimble/port/include/nimble/nimble_npl_os.h
- tools/font/fontgen.py
- tools/resources/resource_map/resource_generator_font.py
- waftools/cc2564_service_pack_convert.py
- waftools/gitinfo.py
I suspect many of these commits are equally applicable to Snowy as they are Asterix, so pulling them back upstream.
Fixes:
- https://github.com/pebble-dev/pebble-firmware/issues/261
- https://github.com/pebble-dev/pebble-firmware/issues/271
- and probably more things we didn't have bugs for on the upstream
> Pull in some (mostly) Nimble related changes from Core downstream

- third_party/nimble/port/include/cc2564x/syscfg/syscfg.h
- third_party/nimble/syscfg/targets/cc2564x/syscfg.yml
It is not clear how I managed to get a typo in the previous one, given that it worked for me previously!
As always, the penance for not testing precisely the thing you PR is that you end up looking stupid in public.  Hooray, now I look stupid in public!
> nimble/cc2564x: enable flow control on HCI (without the typo this time?)
