pebble-dev/pebble-firmware

.github/workflows/gitlint.yml
.gitlint

Applied rules:
- Built-in rulles: all defaults, except:
- Do not ignore cleanup commits (conflicts with CC2)
- Do not ignore merge commits (they will fail with the rule below)
- Custom title regex, enforce `area[/subarea]: description`, e.g. `docs: add new GSG guide`, `drivers/qspi: fix quad-line access`, etc.
- Contrib rules:
- CC1: require Signed-off-by (DCO)
- CC2: no cleanup commits (fixup!, squash!, amend!)
Ref. https://jorisroovers.com/gitlint/latest/rules/

ci: enable gitlint

---

.gitmodules
src/fw/startup/system_stm32f4xx.c
src/fw/stm32f2xx_flash_fw.ld.template
src/fw/stm32f412_flash_fw.ld.template
src/fw/stm32f439_flash_fw.ld.template
src/fw/stm32f7xx_flash_fw.ld.template
src/fw/vendor/wscript

With these changes and https://github.com/pebble-dev/pebble-firmware/pull/15 you can do:
```
./waf configure --board=snowy_bb2 --nojs --nohash
./waf build
./waf flash
./waf console
```
The same has been tested for silk_bb2, but a further change is required to address a missing font.

Add support for Pebble STM32F4 based boards

---

CONTRIBUTING.md

Add details on what is DCO, and how developers need to adhere to it when submitting patches.

doc: add DCO to contribution guidelines

---

tools/generate_pdcs/pebble_commands.py
tools/generate_pdcs/svg2commands.py

A path like "M5.8,9.1" resulted in a PDC with no points which causes an assert at runtime (eg when scrolling down the launcher to the Workout app). Filtering these out at build time avoids this.
I rendered the SVG with these rows removed and it doesn't appear to make a difference, but I'm not entirely confident in this fix even still...

tools: fix bug where SVG paths with only move commands cause crash

---

.gitmodules

This pull request includes a small change to the `.gitmodules` file. The change updates the URL of the `stm32-sdk` submodule to use HTTPS instead of SSH.
Switching to HTTPS ensures that all contributors, regardless of their SSH configuration or familiarity, can easily clone and work with the repository.

submodule: update STM32 SDK URL to use HTTPS

---

waftools/openocd.py

Accessing the outcome of a map through indices is not possible on Python 3

Fix openocd version detection

---

wscript

allows for the use of a custom qemu bin when running ./waf qemu
I used the same environment variable that is also used in qemu_run.sh

tools: allow use of the PEBBLE_QEMU_BIN environment variable

---

requirements-linux.txt
tools/pebble_ftdi_custom_pids.py
tools/pebble_tty_pyftdi.py
tools/pulse_console.py
tools/pulse_flash_imaging.py

This is slightly awkward because you have to setup the custom PID, so any tool that needs those boards supported has to import and call that function.

tools: make pulse tools work for bigboards with public pyftdi

---

src/bluetooth-fw/nimble/advert.c
src/bluetooth-fw/nimble/id.c
src/bluetooth-fw/nimble/init.c

This is enough to get Pebble advertising over BLE with all the device information set correctly. Note that the Pebble app won't see it because it only considers Pebble 2 when scanning BLE and this can't run on Pebble 2 yet.

fw: ble: implement advertising support

---

src/fw/wscript

We no longer have softdevice, use the entire RAM region.

fw: fix RAM size for asterix

---

.github/workflows/test.yml
tests/fakes/fake_kernel_services_notifications.c
tests/fw/graphics/wscript
tests/fw/pebble_actions/wscript
tests/vendor/duma/wscript
tests/wscript
tools/clar/_clar.py
tools/clar/clar.py
tools/generate_pdcs/pdc_gen.py
tools/pbi2png.py
tools/pdc2png/wscript
tools/tests/wscript
waftools/pebble_test.py
wscript

Restores the `waf test` command, hopefully resolving #46.
Any tests failing to compile were commented out and appended with 'UNIT_TEST_DISABLED' for easy location in the future. Additionally, the entire fw/comm test suite was disabled because of missing bluetooth library headers (GAPAPI.h, GATTAPI.h).
I also added CI steps that run the test suite and parses the output junit.xml file. The test and parse steps are setup to not fail the entire build.

unit_test: Restore 'waf test' functionality

---

tools/generate_native_sdk/parse_c_decl.py

In some environments, the parse_file function in the `tools/generate_native_sdk/parse_c_decl.py` script does not add the `-ffreestanding` parameter to the call to gcc, which results in the wrong header file being used by gcc

fix: some cases where the correct stdint.h header file may not be found

---

src/bluetooth-fw/nimble/advert.c

PebbleOS may try to stop advertising at times when NimBLE has already done that (e.g. when connected). Upper layer state machine may be corrected in the future if we converge to a single BLE host stack.

bluetooth-fw/nimble: do not stop adv if not active

---

src/bluetooth-fw/nimble/gap_le_device_name.c

This makes it so that the device name of the paired phone appears in the settings menu.

bluetooth: implement gap_le_device_name

---

src/bluetooth-fw/nimble/gap_le_device_name.c

I handled EDONE wrong, this gets called when we're done reading, it's just that in our case we're only reading one thing.

bluetooth: fix error in prv_device_name_read_event_cb

---

tools/gdb_scripts/gdb_utils.py

```plaintext
tools/gdb_scripts/gdb_utils.py:72: SyntaxWarning: invalid escape sequence '\s'
ADDR_REGEX = re.compile("^\s*(0x[a-fA-F0-9]{7,8})")
```
Signed-off-by: Noah Pendleton <noah.pendleton@gmail.com>

tools: fix syntaxwarning on python 3.12+

---

src/fw/drivers/nrf5/stubs/otp.c
src/fw/mfg/asterix/mfg_info.c
src/fw/mfg/mfg_serials.c

The iOS app gets quite upset if there is no serial number or MFG data, and the current fake OTP data incorrectly reports that it is programmed already.  Later, we should implement OTP in terms of UICR (FIRM-35) but for now at least we should not report it as programmed if it is not.

asterix: add some fake OTP / serial data until we have a real mfg flow

---

src/fw/main.c

On nRF, PMIC powers flash, so flash_init() may fail on very first cold boot. This issue has likely been masked because we reset so often while debugging, and PMIC is never set into its reset state.
One day we need a proper driver architecture with dependency support etc. so we do not depend on fragile C code level ordering.

fw: init PMIC before flash

---

.gitmodules
src/bluetooth-fw/nimble/nimble_store.c
src/fw/services/normal/bluetooth/bluetooth_persistent_storage.c
third_party/nimble/port/include/cc2564x/syscfg/syscfg.h
third_party/nimble/port/include/nrf52/syscfg/syscfg.h
third_party/nimble/syscfg/targets/cc2564x/syscfg.yml

This appears to be needed on snowy even if it isn't needed on nrf: the LTK isn't the same for our/peer and if we return the wrong one the remote drops the connection.
I had to switch to the v2 bonding store format even though that wasn't previously used on CC2564x based devices. Bluetopia used ediv/div to store local encryption info, but Nimble uses ediv/rand/LTK and it seems to be non-trivial to adapt Nimble to use the Bluetopia stored values.
This is a bit of a problem because if you have bondings, the v2 code asserts when reading the bonding storage, but it's something I'll have to come back and fix later...

Fix bonding and reconnections for cc2564x

---

waftools/pebble_arm_gcc.py

Unfortunately `emcc` is not currently cacheable by `ccache` to my
knowledge, so this only helps with ~ 1000 / 1750 objects.
Signed-off-by: Noah Pendleton <noah.pendleton@gmail.com>

waftools: use `ccache` when available

---

src/fw/drivers/wscript_build

Note that some drivers are still stubs (added FIXME comments). Some PebbleOS abstractions likely need a rethink, as they are STM32-biased.

fw/drivers: de-hack asterix driver build

---

docs/getting_started.md

- Clone after pre-requisites, otherwise git is not installed
- Add missing packages (clang, git, python3-dev)
- Fix venv creation using python3 (yes, Ubuntu still sucks with Python)
- Add hints to verify compiler
- Add clarification notes to emsdk install
- Use Ubuntu 24.04 LTS (to emphasize we support LTS)

docs/gsg: fixes/improvements for Ubuntu 24.04 LTS

---

src/fw/flash_region/flash_region.h
src/fw/flash_region/flash_region_gd25lq255e.h

Until now Silk layout was used, so only 8MB were effectively available instead of 32MB.

fw/flash_region: add flash region for GD25LQ255E

---

python_libs/pebble-commander/pebble/commander/_commands/imaging.py
src/fw/drivers/nrf5/qspi.c
src/fw/drivers/qspi_definitions.h
src/fw/system/logging.h

This PR resolves a long-standing issue with _long_ flash transfers leading to data corruption. It looks like it was mainly due to the flash clock speed being too high. For now, I've reduced flash clock from 32MHz to 8MHz. I guess 32MHz would require a better layout.
I have also taken the opportunity to do some cleanups to the nRF QSPI driver. Note that despite nRF PS claiming flash address needs to be word-aligned, this is not what I observe. Maybe some flash devices require word-aligned access (not GD25LQ255E), and this was incorrectly propagated to the PS.
I have also disabled BT logs by default, as they flood flash_logging when doing BLE file transfers, when you precisely want flash maximum bandwidth.
When flashing resources over pulse, the issue is never observed, however, when …

nRF QSPI fixes/improvements

---

docs/legacy/porting-bluetooth.md
src/bluetooth-fw/nimble/advert.c
src/bluetooth-fw/qemu/advert.c
src/bluetooth-fw/stub/advert.c
src/fw/comm/ble/gap_le_advert.c
src/include/bluetooth/bt_driver_advert.h

This code is currently causing issues on Asterix when tearing down the
system (assert). It doesn't seem to be necessary for Snowy under NimBLE.

bluetooth-fw: drop advert workaround APIs

---

.github/workflows/compliance.yml

This reverts commit e9d0ffdbf6fc342ef11abe4f4e0ec308c9b8f4f3.
Let's tune .clang-format, re-format the codebase and add this back.

Revert "ci: compliance: add clang-format check"

---

docs/legacy/porting-bluetooth.md
src/bluetooth-fw/nimble/pebble_pairing_service.c
src/bluetooth-fw/qemu/pebble_pairing_service.c
src/bluetooth-fw/stub/pebble_pairing_service.c
src/fw/comm/ble/gatt.c
src/include/bluetooth/pebble_pairing_service.h

Note that for now the preferred MTU stays at 256 (NimBLE default), increasing it requires to re-dimension buffers, it may be explored in the future.

bluetooth-fw: remove GATT MTU service

---

python_libs/pbl/pbl/__init__.py
python_libs/pbl/pbl/commands/coredump.py

This also needs some changes elsewhere (in particular, it needs pebble-dev/libpebble2 in order to work right), but this is at least necessary if not sufficient to be able to pull a core dump over PULSE2.

pbltool: modernize for Python3

---

src/fw/console/prompt_commands.c
src/fw/console/prompt_commands.h

Previously, `prompt_commands` offered a `flash stress` that ran forever, but didn't check its work -- and continuously erased and re-erased sectors.  Also, it wrote to the log region, which was going to be used by other things!  It would be better to use as large of a region of flash as possible to write to, so we distribute the load -- and it would be nice to only erase when we have to, and to be able to check our work.
The new `flash stress` overwrites the update scratch region, and does a readback test, and uses a PRNG to compare repeatedly, and can test many different sizes and offsets of flash writes.  This `flash stress` can meaningfully find failures on asterix-evt1 when QSPI is run at 32MHz.

console: add "flash stress" command that is somewhat more aggressive

---

src/fw/services/normal/data_logging/dls_endpoint.c
src/fw/services/normal/data_logging/dls_list.c
src/fw/services/normal/data_logging/dls_list.h

It looks like DLS had a deadlock case between two recursive mutexes. Incidence seems to be _random_, but with current main high enough to freeze the watch just a few minutes after connecting to a phone. Below you will find a detailed analysis.
Tasks:
- `PebbleTask_KernelBackground`
- `PebbleTask_NewTimers`
Mutexes with circular dependency:
- `s_list_mutex` (`dls_list.c`)
- `s_endpoint_data.mutex` (`dls_endpoint.c`)
Measured condition:
```
! PebbleTask_KernelBackground [
dls_list_for_each_session(callback=prv_send_session)
mutex_lock_recursive: s_list_mutex
prv_send_session
dls_private_send_session
dls_endpoint_send_data
> PREEMPTION
! PebbleTask_NewTimers [
ack_timer_cb
mutex_lock: s_endpoint_data.mutex
check_ack_timeout
dls_list_for_each_session(
callback=check_ack_timeout_for_session
) …
```

fw/services/data_logging: fix deadlock

---

src/fw/apps/prf_apps/recovery_first_use_app/recovery_first_use_app.c

PRF Icon offset was overriden to use a seperate fullscreen bitmap which isn't present on asterix, so this will just exclude it from the override restoring the centered icon in PRF

fw/apps/prf: center icon on asterix [FIRM-97]

---

src/bluetooth-fw/nimble/advert.c
src/bluetooth-fw/nimble/nimble_store.c
src/fw/services/common/bluetooth/bluetooth_persistent_storage.h
src/fw/services/normal/bluetooth/bluetooth_persistent_storage.c
src/fw/services/prf/bluetooth/bluetooth_persistent_storage.c

If a phone deletes pairing information and watch is left in PRF mode
we won't be able to connect again because NimBLE doesn't handle the
repeat pairing event. While in normal firmware, we can always go to BT
settings menu and delete a pairing, we cannot in PRF. Ideally, we should
warn users about this event. This is left as a TODO for now.

Add support for repeat pairing event

---

sdk/tools/inject_metadata.py

> This fixes readelf parsing for SDK builds when an ELF has more than 100 sections. The parsing logic previously assumed that section IDs could only go up to 99 (2 digits), this makes it look for a closing bracket instead.
This is #34 but with (my) sign-off in the commit message, as per the original author's permission here: https://github.com/pebble-dev/pebble-firmware/pull/34#issuecomment-2868362926

tools: fix readelf parsing with more than 100 sections

---

src/fw/drivers/battery.h
src/fw/drivers/battery/battery_pmic.c
src/fw/drivers/battery/battery_tintin.c
src/fw/drivers/pmic/npm1300.c
src/fw/drivers/qemu/qemu_battery.c
src/fw/services/common/battery/battery_monitor.c
src/fw/services/common/battery/battery_state.c
src/fw/services/common/battery/battery_state.h

Regardless of the battery state, stay in good state if the watch is plugged. This can happen e.g. in development where the battery is in reality a power source that can be turned off if operating from VUSB only. In a real watch, this will just happen if battery is completely dead, but still, allow using the watch if plugged. Nordic PMIC will by default not even try to charge a battery like that. If this is a safety concern for older designs this can be made configurable.

fw/services/battery: do not trigger LP/critical states if plugged

---

.gitlint
src/fw/drivers/nrf5/rtc.c
third_party/nimble/port/include/nrf52/syscfg/syscfg.h
third_party/nimble/syscfg/targets/nrf52/syscfg.yml

Some evt2s appear to have an LFXO that is off by as much as 350ppm, as measured on a scope, or more, if measured with LFSYNTH vs. LFXTAL; this causes BLE to fail to connect.  Work around this until such time as the hardware is fixed for certain.

asterix: work around busted LFXOs on some evt2s by increasing SCA tolerance

---

tools/pebble_tty_pyftdi.py

Previously, we would select:
`No --tty argument specified, auto-selecting: ftdi://ftdi:2232:TG110ae9/2`
But that won't do at all -- it will select the JTAG port on the Tigard.  Not very useful as a serial port.  Now, we select:
`No --tty argument specified, auto-selecting: ftdi://ftdi:2232:TG110ae9/1`
Much better.

tools/pebble_tty: if we select a Tigard as a dbgserial, select the correct port

---

src/fw/drivers/display/display.h

display.h uses `struct GPoint`, but it does not include its definition header. Things likely worked because of indirect include chain. This likely needs a proper cleanup, but allows to compile for now.

fw/drivers/display: add missing include

---

src/fw/apps/system_apps/alarms/alarm_editor.c

For ARRAY_LENGTH(), this worked because... board files included it!

fw/apps/alarm_editor: add missing include

---

src/fw/fw_common.ld
src/fw/nrf52840_flash_fw.ld.template
src/fw/stm32f2xx_flash_fw.ld.template
src/fw/stm32f412_flash_fw.ld.template
src/fw/stm32f439_flash_fw.ld.template
src/fw/stm32f7xx_flash_fw.ld.template

If any SoC adds a new section to flash, it will get the first offset, triggering the ISR vector section assert. None of the existing SoCs needed to add new sections, so it has been ok to keep the entry in the common file until now. However, SF32LB will need to add an extra entry that triggers this problem. If we ever preprocess the ld files, or generate them in a more advanced manner, we could improve this, but now I do not see any other immediate solution (maybe I'm just tired).

fw: move vector table section into every soc file

---

src/fw/drivers/nrf5/rtc.c

Changes introduced in ab8a04fe1b5192f71c3edee36444ccfe9b824f84. Main firmware crashes and so it is unbootable, reverting for now.
I could not apply a clean revert as other conflicting changes have gone into main, so this is a manual revert.

fw/drivers/nrf5/rtc: revert RTC alarm changes

---

waftools/pebble_arm_gcc.py

a trivial quality-of-life thing that bit me.  now you can `./waf configure --board snowy_bb2 --nostop --nojs --nohash --nosleep --nowatchdog --nolto`!

waftools: everything else is spelled --nofoo rather than --no-foo; --nolto can be too

---

third_party/nimble/port/include/cc2564x/syscfg/syscfg.h
third_party/nimble/syscfg/targets/cc2564x/syscfg.yml
third_party/nimble/transport/hci_uart_transport.c

Enables flow control for HCI, and makes as surgical of restructuring of the interrupt handler as possible such that deallocation happens on the high-priority NimBLE UART thread, rather than on the main thread.
Fixes #245 (I hope).  With this fix, I spent most of an evening banging on it trying to get it to blow up, without tripping it at all (though last night I did see it regularly, which makes me think I must have forgotten to recompile before I flashed my device, or something).  Without this fix, I crash within two connection attempts with the `HCI_H4_ACL buf alloc` fault.

nimble/cc2564x: turn on flow control for HCI

---

platform/platform_capabilities.py
src/fw/services/normal/bluetooth/bluetooth_persistent_storage.c

snowy uses v1 of bluetooth_persistent_storage, which NimBLE does not support.  As it turns out, we are generally not very robust against gap_bondings that we don't know how to deal with, and we can crash the system if they happen!  Let's rather ignore them, in case a future PebbleOS version extends the gap_bonding structure in a way that we don't know how to read and someone tries to downgrade.
And just like we choked on gap_bonding_dbs from formerly-Bluetopia devices, formerly-Bluetopia devices may behave very strangely indeed on ours.  On those devices, rename the bonding DB so it's not a problem.
Fixes https://github.com/pebble-dev/pebble-firmware/issues/253.

do not choke on gap_bondings of the wrong version
